In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../../data/processed/day11_customer_segmentation.csv")

In [3]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Avg_Monthly_Spend,Tenure_Group,Charge_Segment
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,14.925000,New,Low
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,One year,No,Mailed check,56.95,1889.50,No,53.985714,Loyal,Medium
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,36.050000,New,Medium
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,40.016304,Loyal,Medium
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,50.550000,New,High

In [4]:
df['Contract_Risk'] = df['Contract'].map({
    'Month-to-month': 3,
    'One year': 2,
    'Two year': 1
})

In [5]:
df[['Contract','Contract_Risk']].head(10)

         Contract  Contract_Risk
0  Month-to-month              3
1        One year              2
2  Month-to-month              3
3        One year              2
4  Month-to-month              3
5  Month-to-month              3
6  Month-to-month              3
7  Month-to-month              3
8  Month-to-month              3
9        One year              2

In [6]:
df['TotalCharges'] = pd.to_numeric(
    df['TotalCharges'],
    errors='coerce'
)

In [7]:
df['TotalCharges'] = df['TotalCharges'].fillna(
    df['TotalCharges'].median()
)

In [8]:
df['Revenue_Per_Tenure'] = (
    df['TotalCharges'] /
    (df['tenure'] + 1)
)

In [9]:
df[['TotalCharges',
    'tenure',
    'Revenue_Per_Tenure']].head(10)

   TotalCharges  tenure  Revenue_Per_Tenure
0         29.85       1           14.925000
1       1889.50      34           53.985714
2        108.15       2           36.050000
3       1840.75      45           40.016304
4        151.65       2           50.550000
5        820.50       8           91.166667
6       1949.40      22           84.756522
7        301.90      10           27.445455
8       3046.05      28          105.036207
9       3487.95      62           55.364286

In [10]:
df[['Tenure_Group',
    'Charge_Segment',
    'Contract_Risk',
    'Revenue_Per_Tenure']].head()

  Tenure_Group Charge_Segment  Contract_Risk  Revenue_Per_Tenure
0          New            Low              3           14.925000
1        Loyal         Medium              2           53.985714
2          New         Medium              3           36.050000
3        Loyal         Medium              2           40.016304
4          New           High              3           50.550000

In [11]:
df.to_csv(
    "../../data/processed/feature_engineered_telco.csv",
    index=False
)