In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../../data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [3]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [4]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

In [5]:
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [8]:
df['TotalCharges'] = df['TotalCharges'].fillna(df['TotalCharges'].median())

In [9]:
df['TotalCharges'].isnull().sum()

np.int64(0)

In [10]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Churn'] = le.fit_transform(df['Churn'])

In [11]:
df['Churn'].head()

0    0
1    0
2    1
3    0
4    1
Name: Churn, dtype: int64

In [12]:
df_encoded = pd.get_dummies(df, drop_first=True)

In [13]:
df_encoded.shape

(7043, 7073)

In [14]:
df = df.drop('customerID', axis=1)

In [15]:
df.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [16]:
df['Tenure_Group'] = pd.cut(
    df['tenure'],
    bins=[0,12,24,48,72],
    labels=['0-12','13-24','25-48','49-72']
)

In [17]:
df['Tenure_Group'].value_counts()

Tenure_Group
49-72    2239
0-12     2175
25-48    1594
13-24    1024
Name: count, dtype: int64

In [18]:
df['Charge_Segment'] = pd.cut(
    df['MonthlyCharges'],
    bins=[0,35,70,120],
    labels=['Low','Medium','High']
)

In [19]:
df['Charge_Segment'].value_counts()

Charge_Segment
High      3583
Low       1735
Medium    1725
Name: count, dtype: int64

In [20]:
df[['tenure','Tenure_Group','MonthlyCharges','Charge_Segment']].head()

   tenure Tenure_Group  MonthlyCharges Charge_Segment
0       1         0-12           29.85            Low
1      34        25-48           56.95         Medium
2       2         0-12           53.85         Medium
3      45        25-48           42.30         Medium
4       2         0-12           70.70           High

In [21]:
selected_features = [
    'tenure',
    'MonthlyCharges',
    'TotalCharges',
    'Churn'
]

df[selected_features].head()

   tenure  MonthlyCharges  TotalCharges  Churn
0       1           29.85         29.85      0
1      34           56.95       1889.50      0
2       2           53.85        108.15      1
3      45           42.30       1840.75      0
4       2           70.70        151.65      1