In [1]:
import pandas as pd

df = pd.read_csv("../../data/processed/feature_engineered_telco.csv")

In [2]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Avg_Monthly_Spend,Tenure_Group,Charge_Segment,Contract_Risk,Revenue_Per_Tenure
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,Yes,Electronic check,29.85,29.85,No,14.925000,New,Low,3,14.925000
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,Mailed check,56.95,1889.50,No,53.985714,Loyal,Medium,2,53.985714
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,Yes,Mailed check,53.85,108.15,Yes,36.050000,New,Medium,3,36.050000
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,No,Bank transfer (automatic),42.30,1840.75,No,40.016304,Loyal,Medium,2,40.016304
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,Yes,Electronic check,70.70,151.65,Yes,50.550000,New,High,3,50.550000

In [3]:
df.shape

(7043, 26)

In [4]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn',
       'Avg_Monthly_Spend', 'Tenure_Group', 'Charge_Segment', 'Contract_Risk',
       'Revenue_Per_Tenure'],
      dtype='str')

In [5]:
from sqlalchemy import create_engine

In [6]:
engine = create_engine(
    "postgresql://postgres:MyNewPassword123@localhost:5432/telco_churn_db"
)

In [7]:
df.to_sql(
    "telco_customers",
    engine,
    if_exists="replace",
    index=False
)

43

In [8]:
query = "SELECT * FROM telco_customers LIMIT 5"

pd.read_sql(query, engine)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Avg_Monthly_Spend,Tenure_Group,Charge_Segment,Contract_Risk,Revenue_Per_Tenure
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,Yes,Electronic check,29.85,29.85,No,14.925000,New,Low,3,14.925000
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,Mailed check,56.95,1889.50,No,53.985714,Loyal,Medium,2,53.985714
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,Yes,Mailed check,53.85,108.15,Yes,36.050000,New,Medium,3,36.050000
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,No,Bank transfer (automatic),42.30,1840.75,No,40.016304,Loyal,Medium,2,40.016304
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,Yes,Electronic check,70.70,151.65,Yes,50.550000,New,High,3,50.550000